### ISSUE TITLE
11.5 Spring---WebClient介绍

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/javaway#52]
Spring---WebClient介绍- Elim的博客- ITeye博客
elim.iteye.com/blog/2427658

WebClient是从Spring WebFlux 5.0版本开始提供的一个非阻塞的基于响应式编程的进行Http请求的客户端工具。它的响应式编程的基于Reactor的。WebClient中提供了标准Http请求方式对应的get、post、put、delete等方法，可以用来发起相应的请求。

**Comment by vieyahn2017** [comment]
下面的代码是一个简单的WebClient请求示例。可以通过WebClient.create()创建一个WebClient的实例，之后可以通过get()、post()等选择调用方式，uri()指定需要请求的路径，retrieve()用来发起请求并获得响应，bodyToMono(String.class)用来指定请求结果需要处理为String，并包装为Reactor的Mono对象。
```java
WebClient webClient = WebClient.create();
Mono<String> mono = webClient.get().uri("https://www.baidu.com").retrieve().bodyToMono(String.class);
mono.subscribe(System.out::println);
```

### 响应结果解析为对象
当响应的结果是JSON时，也可以直接指定为一个Object，WebClient将接收到响应后把JSON字符串转换为对应的对象。比如下面这样。
```java
WebClient webClient = WebClient.create();
Mono<User> mono = webClient.get().uri("http://localhost:8081/user/1").retrieve().bodyToMono(User.class);
User user = mono.block();
```
如果响应的结果是一个集合，则不能继续使用bodyToMono()，应该改用bodyToFlux()，然后依次处理每一个元素，比如下面这样。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);
Flux<User> userFlux = webClient.get().uri("users").retrieve().bodyToFlux(User.class);
userFlux.subscribe(System.out::println);
```
如果需要通过Flux取到所有的元素构造为一个List，则可以通过如下的方式获取。
```java
List<User> users = userFlux.collectList().block();
```

### URL中使用路径变量
URL中也可以使用路径变量，路径变量的值可以通过uri方法的第2个参数指定。下面的代码中就定义了URL中拥有一个路径变量id，然后实际访问时该变量将取值1。
```java
webClient.get().uri("http://localhost:8081/user/{id}", 1);
```
URL中也可以使用多个路径变量，多个路径变量的赋值将依次使用uri方法的第2个、第3个、第N个参数。下面的代码中就定义了URL中拥有路径变量p1和p2，实际访问的时候将被替换为var1和var2。所以实际访问的URL是http://localhost:8081/user/var1/var2。
```java
webClient.get().uri("http://localhost:8081/user/{p1}/{p2}", "var1", "var2");
```
使用的路径变量也可以通过Map进行赋值。面的代码中就定义了URL中拥有路径变量p1和p2，实际访问的时候会从uriVariables中获取值进行替换。所以实际访问的URL是http://localhost:8081/user/var1/1
```java
Map<String, Object> uriVariables = new HashMap<>();
uriVariables.put("p1", "var1");
uriVariables.put("p2", 1);
webClient.get().uri("http://localhost:8081/user/{p1}/{p2}", uriVariables);
```

### 指定baseUrl
在应用中使用WebClient时也许你要访问的URL都来自同一个应用，只是对应不同的URL地址，这个时候可以把公用的部分抽出来定义为baseUrl，然后在进行WebClient请求的时候只指定相对于baseUrl的URL部分即可。这样的好处是你的baseUrl需要变更的时候可以只要修改一处即可。下面的代码在创建WebClient时定义了baseUrl为http://localhost:8081，在发起Get请求时指定了URL为/user/1，而实际上访问的URL是http://localhost:8081/user/1。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);
Mono<User> mono = webClient.get().uri("user/{id}", 1).retrieve().bodyToMono(User.class);
```

### Form提交
当传递的请求体对象是一个MultiValueMap对象时，WebClient默认发起的是Form提交。下面的代码中就通过Form提交模拟了用户进行登录操作，给Form表单传递了参数username，值为u123，传递了参数password，值为p123。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);

MultiValueMap<String, String> map = new LinkedMultiValueMap<>();
map.add("username", "u123");
map.add("password", "p123");

Mono<String> mono = webClient.post().uri("/login").syncBody(map).retrieve().bodyToMono(String.class);
```

### 请求JSON
假设现在拥有一个新增User的接口，按照接口定义客户端应该传递一个JSON对象，格式如下：
```
{
    "name":"张三",
    "username":"zhangsan"
}
```
客户端可以建立一个满足需要的JSON格式的对象，然后直接把该对象作为请求体，WebClient会帮我们自动把它转换为JSON对象。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);

User user = new User();
user.setName("张三");
user.setUsername("zhangsan");

Mono<Void> mono = webClient.post().uri("/user/add").syncBody(user).retrieve().bodyToMono(Void.class);
mono.block();
```
如果没有建立对应的对象，直接包装为一个Map对象也是可以的，比如下面这样。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);

Map<String, Object> user = new HashMap<>();
user.put("name", "张三");
user.put("username", "zhangsan");

Mono<Void> mono = webClient.post().uri("/user/add").syncBody(user).retrieve().bodyToMono(Void.class);
mono.block();
```
直接传递一个JSON字符串也是可以的，但是此时需要指定contentType为application/json，也可以加上charset。默认情况下WebClient将根据传递的对象在进行解析处理后自动选择ContentType。直接传递字符串时默认使用的ContentType会是text/plain。其它情况下也可以主动指定ContentType。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);

String userJson = 
        "{" + 
        "    \"name\":\"张三\",\r\n" + 
        "    \"username\":\"zhangsan\"\r\n" + 
        "}";

Mono<Void> mono = webClient.post().uri("/user/add").contentType(MediaType.APPLICATION_JSON_UTF8).syncBody(userJson).retrieve().bodyToMono(Void.class);
mono.block();
```

### exchange
前面介绍的示例都是直接获取到了响应的内容，可能你会想获取到响应的头信息、Cookie等。那就可以在通过WebClient请求时把调用retrieve()改为调用exchange()，这样可以访问到代表响应结果的org.springframework.web.reactive.function.client.ClientResponse对象，通过它可以获取响应的状态码、Cookie等。下面的代码先是模拟用户进行了一次表单的登录操作，通过ClientResponse获取到了登录成功后的写入Cookie的sessionId，然后继续请求了用户列表。在请求获取用户列表时传递了存储了sessionId的Cookie。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.create(baseUrl);

MultiValueMap<String, String> map = new LinkedMultiValueMap<>();
map.add("username", "u123");
map.add("password", "p123");

Mono<ClientResponse> mono = webClient.post().uri("login").syncBody(map).exchange();
ClientResponse response = mono.block();
if (response.statusCode() == HttpStatus.OK) {
    Mono<Result> resultMono = response.bodyToMono(Result.class);
    resultMono.subscribe(result -> {
        if (result.isSuccess()) {
            ResponseCookie sidCookie = response.cookies().getFirst("sid");
            Flux<User> userFlux = webClient.get().uri("users").cookie(sidCookie.getName(), sidCookie.getValue()).retrieve().bodyToFlux(User.class);
            userFlux.subscribe(System.out::println);
        }
    });
}
```

### WebClient.Builder
除了可以通过WebClient.create()创建WebClient对象外，还可以通过WebClient.builder()创建一个WebClient.Builder对象，再对Builder对象进行一些配置后调用其build()创建WebClient对象。下面的代码展示了其用法，配置了baseUrl和默认的cookie信息。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.builder().baseUrl(baseUrl).defaultCookie("cookieName", "cookieValue").build();
```
Builder还可以通过clientConnector()定义需要使用的ClientHttpConnector，默认将使用org.springframework.http.client.reactive.ReactorClientHttpConnector，其底层是基于netty的，如果你使用的是Maven，需要确保你的pom.xml中定义了如下依赖。
```xml
<dependency>
    <groupId>io.projectreactor.ipc</groupId>
    <artifactId>reactor-netty</artifactId>
    <version>0.7.8.RELEASE</version>
</dependency>
```
如果对默认的发送请求和处理响应结果的编解码不满意，还可以通过exchangeStrategies()定义使用的ExchangeStrategies。ExchangeStrategies中定义了用来编解码的对象，其也有对应的build()方法方便我们来创建ExchangeStrategies对象。
WebClient也提供了Filter，对应于org.springframework.web.reactive.function.client.ExchangeFilterFunction接口，其接口方法定义如下。
Mono<ClientResponse> filter(ClientRequest request, ExchangeFunction next)
在进行拦截时可以拦截request，也可以拦截response。下面的代码定义的Filter就拦截了request，给每个request都添加了一个名为header1的header，值为value1。它也拦截了response，response中也是添加了一个新的header信息。拦截response时，如果新的ClientResponse对象是通过ClientResponse.from(response)创建的，新的response是不会包含旧的response的body的，如果需要可以通过ClientResponse.Builder的body()指定，其它诸如header、cookie、状态码是会包含的。
```java
String baseUrl = "http://localhost:8081";
WebClient webClient = WebClient.builder().baseUrl(baseUrl).filter((request, next) -> {
    ClientRequest newRequest = ClientRequest.from(request).header("header1", "value1").build();
    Mono<ClientResponse> responseMono = next.exchange(newRequest);
    return Mono.fromCallable(() -> {
        ClientResponse response = responseMono.block();
        ClientResponse newResponse = ClientResponse.from(response).header("responseHeader1", "Value1").build();
        return newResponse;
    });
}).build();
```
如果定义的Filter只期望对某个或某些request起作用，可以在Filter内部通过request的相关属性进行拦截，比如cookie信息、header信息、请求的方式或请求的URL等。也可以通过ClientRequest.attribute(attrName)获取某个特定的属性，该属性是在请求时通过attribute("attrName", "attrValue")指定的。这跟在HttpServletRequest中添加的属性的作用范围是类似的。
关于WebClient使用的更多信息请参考其API文档。


参考文档
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-client
（注：本文是基于Spring WebFlux 5.0.7所写）

**Comment by vieyahn2017** [comment]
Spring WebClient与RestTemplate性能对比——响应式Spring的道法术器

2018年03月10日 11:35:04 享学IT 阅读数：3657 标签： 响应式  WebClient
个人分类： 【打怪升级】Spring响应式编程
所属专栏： 响应式Spring的道法术器
版权声明：本文为博主原创文章，未经博主允许不得转载。  https://blog.csdn.net/get_set/article/details/79506373
本系列其他文章见：《响应式Spring的道法术器》。 
前情提要：Spring WebFlux快速上手 | Spring WebFlux性能测试 
本文源码

1.4.2 调用带有延迟的服务负载分析

由于微服务架构的盛行，大型系统内服务间基于HTTP API进行调用的会相当频繁。Netflix的系统有500+的微服务，感受一下~

我们的测试如下图所示，服务A调用服务B的API，从服务A发出请求到接收到响应，期间可能存在延迟，比如网络不稳定、服务B不稳定，或因为所请求的API本身执行时间略长等等。对于作为HTTP客户端的服务A来说，是否能够异步地处理对服务B的请求与响应，也会带来明显的性能差异。我们通过简单的场景模拟一下：



通过上一个测试，我们已经确定WebFlux-with-latency的API /hello/{latency}能够在高并发下，仍然以稳定的latency~latency+5ms的延迟做出响应，因此用来作为被调用的服务B，模拟带有延迟的服务。这样如果测试结果出现明显的差异，那么可以排除服务B的原因。

本次测试我们创建两个服务A的项目：restTemplate-as-caller和webClient-as-caller。它们也都提供URL为/hello/{latency}的API，在API的实现上都是通过Http请求服务A的/hello/{latency}，返回的数据作为自己的响应。区别在于：restTemplate-as-caller使用RestTemplate作为Http客户端，webClient-as-caller使用WebClient作为Http客户端。

## restTemplate-as-caller

使用Spring Initializr创建一个依赖“Web”的项目（也就是WebMVC项目），POM依赖：
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
```        
端口号设置为8093，然后开发/hello/{latency}：
```java
HelloController.java：

    @RestController
    public class HelloController {
        private final String TARGET_HOST = "http://localhost:8092";
        private RestTemplate restTemplate;

        public HelloController() {  // 1
            PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
            connectionManager.setDefaultMaxPerRoute(1000);
            connectionManager.setMaxTotal(1000);
            this.restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory(
                    HttpClientBuilder.create().setConnectionManager(connectionManager).build()
            ));

        }

        @GetMapping("/hello/{latency}")
        public String hello(@PathVariable int latency) {
            return restTemplate.getForObject(TARGET_HOST + "/hello/" + latency, String.class);
        }
    }
```    
由于测试过程中，RestTemplate会发出大量请求，我们在Controller的构造方法中创建一个基于Http连接池构造的RestTemplate，否则可能会把系统能给的端口用尽而出错；
使用RestTemplate请求服务B，并将响应返回。
启动服务WebFlux-with-latency和restTemplate-as-caller。

这个测试我们并不需要分析1000~10000的不同用户量场景下的响应时长的变化趋势，只是验证RestTemplate的阻塞性，所以直接测试一下6000用户，测试结果如下：



吞吐量为1651req/sec，95%响应时长为1622ms。

与1.4.1中mvc-with-latency的6000用户的结果类似，可见RestTemplate确实是会阻塞的。好吧，其实写个小@Test就能测出来是不是阻塞的，不过我的用意不仅限于此，下边我们进行一个响应式改造。首先请回忆前边介绍的两个内容：

不知道你是否还记得在1.3.3.1的最后提过，用Spring WebMVC + Reactor（spring-boot-starter-web+reactor-core）也可以像WebFlux一样实现基于注解的响应式编程；
在1.3.2.5介绍过如何利用elastic的调度器将阻塞的调用转化为异步非阻塞的。
基于此，我们来改一下代码。首先在pom.xml中增加reactor-core：
```xml
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.1.4.RELEASE</version>
        </dependency>
```
然后RestTemplate的调用转为异步：
```java
    @GetMapping("/hello/{latency}")
    public Mono<String> hello(@PathVariable int latency) {
        return Mono.fromCallable(() -> restTemplate.getForObject(TARGET_HOST + "/hello/" + latency, String.class))
                .subscribeOn(Schedulers.elastic());
    }
```
再次测试，发现结果有了明显改善：



吞吐量为2169 req/sec，95%响应时长为121ms。

但是，使用Schedulers.elastic()其实就相当于将每一次阻塞的RestTemplate调用调度到不同的线程里去执行，效果如下：



因为不仅有处理请求的200个线程，还有Schedulers.elastic()给分配的工作线程，所以总的线程数量飙到了1000多个！不过在生产环境中，我们通常不会直接使用弹性线程池，而是使用线程数量可控的线程池，RestTemplate用完所有的线程后，更多的请求依然会造成排队的情况。

这一点使用Schedulers.newParallel()的调度器一测便知。
```java
    @RestController
    public class HelloController {
        private final String TARGET_HOST = "http://localhost:8092";
        private RestTemplate restTemplate;
        private Scheduler fixedPool;

        public HelloController() {
            PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
            connectionManager.setDefaultMaxPerRoute(1000);
            connectionManager.setMaxTotal(1000);
            this.restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory(
                    HttpClientBuilder.create().setConnectionManager(connectionManager).build()
            ));
            fixedPool = Schedulers.newParallel("poolWithMaxSize", 400); // 1
        }

        @GetMapping("/hello/{latency}")
    //    public String hello(@PathVariable int latency) {
    //        return restTemplate.getForObject(TARGET_HOST + "/hello/" + latency, String.class);
    //    }
        public Mono<String> hello(@PathVariable int latency) {
            return Mono.fromCallable(() -> restTemplate.getForObject(TARGET_HOST + "/hello/" + latency, String.class))
                    .subscribeOn(fixedPool);    // 2
        }
    }
```    
创建一个有最大400个线程的线程池poolWithMaxSize；
调度到这个线程池上。
测试时查看线程数：



可见，最多有400个名为poolWithMaxSize的线程，RestTemplate就工作在这些线程上，相比请求处理线程多了一倍。看一下最终的测试结果：



吞吐量2169req/sec，与弹性线程池的那次相同；95%响应时长为236ms，虽然达不到弹性线程池的效果，但是比完全同步阻塞的方式（RestTemplate在请求处理线程中执行）要好多了。

我们再看看非阻塞的WebClient表现如何吧。

## webClient-as-caller

webClient-as-caller基于WebFlux的依赖，端口号8094，不多说，直接看Controller：
```java
    @RestController
    public class HelloController {
        private final String TARGET_HOST = "http://localhost:8092";
        private WebClient webClient;

        public HelloController() {
            this.webClient = WebClient.builder().baseUrl(TARGET_HOST).build();
        }

        @GetMapping("/hello/{latency}")
        public Mono<String> hello(@PathVariable int latency) {
            return webClient
                    .get().uri("/hello/" + latency)
                    .exchange()
                    .flatMap(clientResponse -> clientResponse.bodyToMono(String.class));
        }
```
跑一下6000用户的测试：



吞吐量2195 req/sec，95%响应时长109ms。

关键的是，WebClient不需要大量并发的线程就可以漂亮地搞定这件事儿了：



## 总结

WebClient同样能够以少量而固定的线程数处理高并发的Http请求，在基于Http的服务间通信方面，可以取代RestTemplate以及AsyncRestTemplate。

异步非阻塞的Http客户端，请认准——WebClient~

下一节，介绍一下微服务先行者、全球最大的视频服务平台Netflix使用异步的Http客户端来改造其微服务网关的案例。

**Comment by debug-LiXiwen** [comment]
Spring4新出的AsyncRestTemplate也是异步非阻塞的，基于回调机制获取调用结果，那么请问AsyncRestTemplate和WebClient有什么区别呢
